#!/bin/bash
if [[ "${DEBUG}" == "true" ]]; then
  set -x
fi
set -euo pipefail

echo "Applying Commit linter."

TARGET_BRANCH=${1:-"main"}
TARGET_HEAD_COMMIT=$(git rev-parse "${TARGET_BRANCH}")

LINT_FILE_PATH=$(get-linter-file-path .commitlintrc)
commitlint --config="${LINT_FILE_PATH}" --from="${TARGET_HEAD_COMMIT}"
