#!/bin/bash
if [[ "${DEBUG}" == "true" ]]; then
  set -x
fi
set -euo pipefail

echo "Applying Commit linter."

TARGET_BRANCH=${1:-"main"}
TARGET_HEAD_COMMIT=$(git rev-parse "${TARGET_BRANCH}")

commitlint --config="${LINT_CONFIG_PATH}"/.commitlintrc --from="${TARGET_HEAD_COMMIT}"
