#!/bin/bash
if [[ "${DEBUG}" == "true" ]]; then
  set -x
fi
set -euo pipefail

echo "Applying Dockerfile linter."

DIR=${1:-"."}
FILES=$(find-unignored-files "${DIR}" "\\(^\\|.*\\/\\)Dockerfile$")

if [[ -z "${FILES}" ]]; then
  exit 0
fi

LINT_FILE_PATH=$(get-linter-file-path .hadolint.yaml)
echo "${FILES}" | xargs hadolint --config "${LINT_FILE_PATH}"
