#!/bin/bash
if [[ "${DEBUG}" == "true" ]]; then
  set -x
fi
set -euo pipefail

echo "Applying YAML linter."

DIR=${1:-"."}
FILES=$(find-unignored-files "${DIR}" ".+\\.ya?ml$")

if [[ -z "${FILES}" ]]; then
  exit 0
fi

LINT_FILE_PATH=$(get-linter-file-path .yamllint)
echo "${FILES}" | xargs yamllint -s -c "${LINT_FILE_PATH}"
